version: "3.7"

services:
  ngrok_composerize:
    image: ngrok/ngrok:3
    container_name: ngrok_composerize_container
    command: http --domain=porpoise-crisp-greatly.ngrok-free.app 3000
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=2lSp0hwPn8PrUnanVri6QoWFBLn_4GLB7BVdKX5rq7rDecfCV
    network_mode: host
    stdin_open: true
    tty: true
